name: l2c

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - pip
  - numpy
  - numba
  - cython
  - fftw
  - mpi4py-fft
  - openblas
  - meson
  - ninja
  - pkg-config
  - mpmath
  - boost
  - pytest
  - scipy
  - sympy
